name: CI

on:
  push:
    branches-ignore:
      - "stable"

jobs:
  promote:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}
      - run: |
          git fetch . HEAD:stable
          git push -f origin stable
